// <auto-generated />
using System;
using MVC.ProductManagement.Infrastructure.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.ProductManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.AllowableStress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("Stress")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialFormId");

                    b.ToTable("AllowableStresses");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.EN13458Calculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DesignPressure")
                        .HasColumnType("float");

                    b.Property<Guid>("InnerHeadMaterialFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InnerHeadMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("InnerHeadMaterialStrength")
                        .HasColumnType("float");

                    b.Property<double>("InnerHeadThickness")
                        .HasColumnType("float");

                    b.Property<Guid>("InnerShellMaterialFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InnerShellMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("InnerShellMaterialStrength")
                        .HasColumnType("float");

                    b.Property<double>("InnerShellThickness")
                        .HasColumnType("float");

                    b.Property<double>("InnerTankTotalLength")
                        .HasColumnType("float");

                    b.Property<double>("LiquidDensity")
                        .HasColumnType("float");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OuterDiameter")
                        .HasColumnType("float");

                    b.Property<Guid>("OuterHeadMaterialFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OuterHeadMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("OuterHeadMaterialStrength")
                        .HasColumnType("float");

                    b.Property<double>("OuterHeadThickness")
                        .HasColumnType("float");

                    b.Property<Guid>("OuterShellMaterialFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OuterShellMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("OuterShellMaterialStrength")
                        .HasColumnType("float");

                    b.Property<double>("OuterShellThickness")
                        .HasColumnType("float");

                    b.Property<double>("OuterTankTotalLength")
                        .HasColumnType("float");

                    b.Property<double>("Pressure")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RoundedInnerHeadThickness")
                        .HasColumnType("float");

                    b.Property<double>("RoundedInnerShellThickness")
                        .HasColumnType("float");

                    b.Property<double>("RoundedOuterHeadThickness")
                        .HasColumnType("float");

                    b.Property<double>("RoundedOuterShellThickness")
                        .HasColumnType("float");

                    b.Property<double>("SectorWidth")
                        .HasColumnType("float");

                    b.Property<double>("ShellLength")
                        .HasColumnType("float");

                    b.Property<double>("StaticPressure")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TestPressure")
                        .HasColumnType("float");

                    b.Property<double>("TotalFilmCost")
                        .HasColumnType("float");

                    b.Property<double>("TotalWeldLength")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("InnerHeadMaterialFormId");

                    b.HasIndex("InnerHeadMaterialId");

                    b.HasIndex("InnerShellMaterialFormId");

                    b.HasIndex("InnerShellMaterialId");

                    b.HasIndex("OuterHeadMaterialFormId");

                    b.HasIndex("OuterHeadMaterialId");

                    b.HasIndex("OuterShellMaterialFormId");

                    b.HasIndex("OuterShellMaterialId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("EN13458Calculations");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Density")
                        .HasPrecision(10, 3)
                        .HasColumnType("float(10)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Standard")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(214),
                            Density = 7850.0,
                            Group = "Fine grain pressure vessel steel",
                            MaterialNumber = "1.0565",
                            Name = "P355NH",
                            Notes = "Normalized delivery condition according to EN 10028-3",
                            Standard = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.MaterialForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormType")
                        .HasColumnType("int");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductStandard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("ThicknessMax")
                        .HasColumnType("float");

                    b.Property<double>("ThicknessMin")
                        .HasColumnType("float");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.Property<double?>("WeldingFactor")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialForms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(270),
                            FormType = 0,
                            MaterialId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Notes = "Standard plate form for P355NH",
                            ProductStandard = "EN 10028-3",
                            Status = 0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 1.0,
                            UnitPrice = 1.5
                        });
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.StorageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StorageTypes");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.YieldStrength", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rm")
                        .HasColumnType("float");

                    b.Property<double>("Rp02")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("ThicknessMax")
                        .HasColumnType("float");

                    b.Property<double>("ThicknessMin")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialFormId");

                    b.ToTable("YieldStrengths");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a260b2c-6abe-4eec-9d53-e1d32f94d63c"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(292),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 355.0,
                            Status = 0,
                            Temperature = 20.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("8c16bdca-eb62-4933-9f15-690ba6024f9a"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(302),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 343.0,
                            Status = 0,
                            Temperature = 50.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("6c60740c-3457-4a66-bc20-1acd8031c720"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(304),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 323.0,
                            Status = 0,
                            Temperature = 100.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("8a2be78c-a570-43a9-8c1f-5ddb85b89f0e"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(306),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 299.0,
                            Status = 0,
                            Temperature = 150.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("25a4f7ae-6179-4b9d-b029-bdaf403e2c26"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(308),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 275.0,
                            Status = 0,
                            Temperature = 200.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("5bacc486-b69b-421a-9a5a-725ee6052047"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(312),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 252.0,
                            Status = 0,
                            Temperature = 250.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("a632358f-bc81-42ed-bb7b-7809b0cf2c09"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(314),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 232.0,
                            Status = 0,
                            Temperature = 300.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("caca039c-3d7d-4cd9-a698-83c003d5de96"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(315),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 214.0,
                            Status = 0,
                            Temperature = 350.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("d5e9b21a-c4f9-457a-a75f-afaebb4d3ae5"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(317),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 202.0,
                            Status = 0,
                            Temperature = 400.0,
                            ThicknessMax = 16.0,
                            ThicknessMin = 1.0
                        },
                        new
                        {
                            Id = new Guid("603e1dc8-d1f9-4272-b7c1-fc7e5dd03117"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(321),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 345.0,
                            Status = 0,
                            Temperature = 20.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("5d531868-10b1-40c4-8216-92d5c9aae8c6"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(322),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 334.0,
                            Status = 0,
                            Temperature = 50.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("f321212b-4c07-4fd5-a027-10a4701b49e6"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(324),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 314.0,
                            Status = 0,
                            Temperature = 100.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("d4348f65-9f2e-4772-a508-a0c846e4601f"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(325),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 291.0,
                            Status = 0,
                            Temperature = 150.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("4cd70aeb-1c88-4eaf-8d6e-b620adc9b287"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(328),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 267.0,
                            Status = 0,
                            Temperature = 200.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("0e1ab3f5-2cc0-4c08-a640-446e54b4b016"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(330),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 245.0,
                            Status = 0,
                            Temperature = 250.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("4cade4f6-8d51-450b-a267-f3573dea9a11"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(332),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 225.0,
                            Status = 0,
                            Temperature = 300.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("f67362f1-2c47-4cd5-96f5-d020d8f1cdc3"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(334),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 208.0,
                            Status = 0,
                            Temperature = 350.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("cb98bda9-1abf-4d8b-a645-a621c34c86b6"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(337),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 490.0,
                            Rp02 = 196.0,
                            Status = 0,
                            Temperature = 400.0,
                            ThicknessMax = 40.0,
                            ThicknessMin = 16.0
                        },
                        new
                        {
                            Id = new Guid("ce108200-415d-422a-bbb1-b4ad782f8ff7"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(338),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 335.0,
                            Status = 0,
                            Temperature = 20.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("f984e5a0-f63e-4e30-9507-94819885be02"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(340),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 324.0,
                            Status = 0,
                            Temperature = 50.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("37861200-56c4-4be6-9a9a-7840135a2225"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(342),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 305.0,
                            Status = 0,
                            Temperature = 100.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("84fe8a1f-fc10-4127-90ac-1ec2efd043f8"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(344),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 282.0,
                            Status = 0,
                            Temperature = 150.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("39b490c3-5723-49d3-b51b-028bb4823737"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(346),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 259.0,
                            Status = 0,
                            Temperature = 200.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("270a5aa2-91e9-43c4-a997-1cd98081ba1b"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(373),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 238.0,
                            Status = 0,
                            Temperature = 250.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("51d8e9f9-1122-4bca-aa39-3827288e86e8"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(375),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 219.0,
                            Status = 0,
                            Temperature = 300.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("181186d2-4f3d-4761-a96a-2e4fdaf8639b"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(378),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 202.0,
                            Status = 0,
                            Temperature = 350.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("373f28ef-aed8-4068-869c-e720e6ca3cf2"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(379),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 470.0,
                            Rp02 = 190.0,
                            Status = 0,
                            Temperature = 400.0,
                            ThicknessMax = 60.0,
                            ThicknessMin = 40.0
                        },
                        new
                        {
                            Id = new Guid("dec14be2-b6ba-4cc9-b23c-cf2ab6652c8f"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(381),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 315.0,
                            Status = 0,
                            Temperature = 20.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("60a6e5ab-f615-4349-852b-3843070ff00d"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(383),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 305.0,
                            Status = 0,
                            Temperature = 50.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("406ec4a8-5582-49ea-af3b-ecf3d73a7634"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(385),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 287.0,
                            Status = 0,
                            Temperature = 100.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("a5aa04a5-0d03-4af8-98b9-c62d726b73c6"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(387),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 265.0,
                            Status = 0,
                            Temperature = 150.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("e1e4e4fc-c60c-4542-bb99-bf4e9bfad0e6"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(388),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 244.0,
                            Status = 0,
                            Temperature = 200.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("8ac3517b-5e21-4837-bb94-de3f18aeddb6"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(390),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 224.0,
                            Status = 0,
                            Temperature = 250.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("d71ce8c2-19d6-463c-9d41-779f1cccea19"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(394),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 206.0,
                            Status = 0,
                            Temperature = 300.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("4d8f1e56-55a0-421a-b7a8-f3f2d4124227"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(395),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 190.0,
                            Status = 0,
                            Temperature = 350.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("c494f37c-8fe4-4903-bdea-a38310be6582"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(397),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 179.0,
                            Status = 0,
                            Temperature = 400.0,
                            ThicknessMax = 100.0,
                            ThicknessMin = 60.0
                        },
                        new
                        {
                            Id = new Guid("0c8443d4-2855-44ef-91b6-baa05e2ce450"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(398),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 305.0,
                            Status = 0,
                            Temperature = 20.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("d987eba1-356d-4255-8e3e-b2f37757d99f"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(401),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 295.0,
                            Status = 0,
                            Temperature = 50.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("8150d946-3ff7-40f9-a116-9e8b62e2079d"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(403),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 277.0,
                            Status = 0,
                            Temperature = 100.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("568384af-03fa-4894-9d0e-e3c509bd3a45"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(404),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 257.0,
                            Status = 0,
                            Temperature = 150.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("487b17c5-39ae-4233-a262-2ca3846c828c"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(406),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 236.0,
                            Status = 0,
                            Temperature = 200.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("d776eb54-838d-45b3-8389-de2caa028a18"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(408),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 216.0,
                            Status = 0,
                            Temperature = 250.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("b950cc0c-04c4-468d-87ff-4c53ad12b290"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(410),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 199.0,
                            Status = 0,
                            Temperature = 300.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("4da0f529-4b8b-4ac8-81b2-25e0ad827732"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(412),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 184.0,
                            Status = 0,
                            Temperature = 350.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("0f4e3ec5-c172-47c8-9399-b6c32363d3b9"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(413),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 460.0,
                            Rp02 = 173.0,
                            Status = 0,
                            Temperature = 400.0,
                            ThicknessMax = 150.0,
                            ThicknessMin = 100.0
                        },
                        new
                        {
                            Id = new Guid("05a20d44-864c-4861-afd0-ae4cf2b92520"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(416),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 295.0,
                            Status = 0,
                            Temperature = 20.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("83ddfc3b-907b-4bcd-954a-a4b2ddb43738"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(417),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 285.0,
                            Status = 0,
                            Temperature = 50.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("74f73c42-c609-46ac-bc89-10d96dc70211"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(419),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 268.0,
                            Status = 0,
                            Temperature = 100.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("ca27c874-ed01-4f0b-84b2-c3b7f381a96f"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(421),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 249.0,
                            Status = 0,
                            Temperature = 150.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("8897b595-66d1-42c1-b258-e3f89ac7e6c1"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(423),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 228.0,
                            Status = 0,
                            Temperature = 200.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("4aa4a1b6-e229-4104-bf39-c7c2bcbb5d6b"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(425),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 209.0,
                            Status = 0,
                            Temperature = 250.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("f722d0f6-e4a8-4101-8fbe-46b970e9042f"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(426),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 192.0,
                            Status = 0,
                            Temperature = 300.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("5c331a73-cc7c-4407-bcd3-26a249769746"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(428),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 178.0,
                            Status = 0,
                            Temperature = 350.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        },
                        new
                        {
                            Id = new Guid("35932265-849c-4539-94f8-955da6f28b9c"),
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2025, 10, 17, 18, 8, 29, 688, DateTimeKind.Utc).AddTicks(431),
                            MaterialFormId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rm = 450.0,
                            Rp02 = 167.0,
                            Status = 0,
                            Temperature = 400.0,
                            ThicknessMax = 250.0,
                            ThicknessMin = 150.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.AllowableStress", b =>
                {
                    b.HasOne("MVC.ProductManagement.Domain.Entities.MaterialForm", "MaterialForm")
                        .WithMany("AllowableStresses")
                        .HasForeignKey("MaterialFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialForm");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.EN13458Calculation", b =>
                {
                    b.HasOne("MVC.ProductManagement.Domain.Entities.MaterialForm", "InnerHeadMaterialForm")
                        .WithMany()
                        .HasForeignKey("InnerHeadMaterialFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.Material", "InnerHeadMaterial")
                        .WithMany()
                        .HasForeignKey("InnerHeadMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.MaterialForm", "InnerShellMaterialForm")
                        .WithMany()
                        .HasForeignKey("InnerShellMaterialFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.Material", "InnerShellMaterial")
                        .WithMany()
                        .HasForeignKey("InnerShellMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.MaterialForm", "OuterHeadMaterialForm")
                        .WithMany()
                        .HasForeignKey("OuterHeadMaterialFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.Material", "OuterHeadMaterial")
                        .WithMany()
                        .HasForeignKey("OuterHeadMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.MaterialForm", "OuterShellMaterialForm")
                        .WithMany()
                        .HasForeignKey("OuterShellMaterialFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.Material", "OuterShellMaterial")
                        .WithMany()
                        .HasForeignKey("OuterShellMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC.ProductManagement.Domain.Entities.StorageType", "StorageService")
                        .WithMany("EN13458Calculations")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InnerHeadMaterial");

                    b.Navigation("InnerHeadMaterialForm");

                    b.Navigation("InnerShellMaterial");

                    b.Navigation("InnerShellMaterialForm");

                    b.Navigation("OuterHeadMaterial");

                    b.Navigation("OuterHeadMaterialForm");

                    b.Navigation("OuterShellMaterial");

                    b.Navigation("OuterShellMaterialForm");

                    b.Navigation("StorageService");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.MaterialForm", b =>
                {
                    b.HasOne("MVC.ProductManagement.Domain.Entities.Material", "Material")
                        .WithMany("Forms")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.YieldStrength", b =>
                {
                    b.HasOne("MVC.ProductManagement.Domain.Entities.MaterialForm", "MaterialForm")
                        .WithMany("YieldStrengths")
                        .HasForeignKey("MaterialFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialForm");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.Material", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.MaterialForm", b =>
                {
                    b.Navigation("AllowableStresses");

                    b.Navigation("YieldStrengths");
                });

            modelBuilder.Entity("MVC.ProductManagement.Domain.Entities.StorageType", b =>
                {
                    b.Navigation("EN13458Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
